version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
  
  frontend:
  backend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  
  mongo:
    image: mongo:7.0
    conteiner_name: mongo
    restart: always
    posts:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: